/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */
package unioeste.compiladores.lex;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KW_AS = 5;
  /** RegularExpression Id. */
  int KW_BREAK = 6;
  /** RegularExpression Id. */
  int KW_CONST = 7;
  /** RegularExpression Id. */
  int KW_CONTINUE = 8;
  /** RegularExpression Id. */
  int KW_CRATE = 9;
  /** RegularExpression Id. */
  int KW_ELSE = 10;
  /** RegularExpression Id. */
  int KW_ENUM = 11;
  /** RegularExpression Id. */
  int KW_EXTERN = 12;
  /** RegularExpression Id. */
  int KW_FALSE = 13;
  /** RegularExpression Id. */
  int KW_FN = 14;
  /** RegularExpression Id. */
  int KW_FOR = 15;
  /** RegularExpression Id. */
  int KW_IF = 16;
  /** RegularExpression Id. */
  int KW_IMPL = 17;
  /** RegularExpression Id. */
  int KW_IN = 18;
  /** RegularExpression Id. */
  int KW_LET = 19;
  /** RegularExpression Id. */
  int KW_LOOP = 20;
  /** RegularExpression Id. */
  int KW_MATCH = 21;
  /** RegularExpression Id. */
  int KW_MOD = 22;
  /** RegularExpression Id. */
  int KW_MOVE = 23;
  /** RegularExpression Id. */
  int KW_MUT = 24;
  /** RegularExpression Id. */
  int KW_PUB = 25;
  /** RegularExpression Id. */
  int KW_REF = 26;
  /** RegularExpression Id. */
  int KW_RETURN = 27;
  /** RegularExpression Id. */
  int KW_SELFVALUE = 28;
  /** RegularExpression Id. */
  int KW_SELFTYPE = 29;
  /** RegularExpression Id. */
  int KW_STATIC = 30;
  /** RegularExpression Id. */
  int KW_STRUCT = 31;
  /** RegularExpression Id. */
  int KW_SUPER = 32;
  /** RegularExpression Id. */
  int KW_TRAIT = 33;
  /** RegularExpression Id. */
  int KW_TRUE = 34;
  /** RegularExpression Id. */
  int KW_TYPE = 35;
  /** RegularExpression Id. */
  int KW_UNSAFE = 36;
  /** RegularExpression Id. */
  int KW_USE = 37;
  /** RegularExpression Id. */
  int KW_WHERE = 38;
  /** RegularExpression Id. */
  int KW_WHILE = 39;
  /** RegularExpression Id. */
  int KW_ASYNC = 40;
  /** RegularExpression Id. */
  int KW_AWAIT = 41;
  /** RegularExpression Id. */
  int KW_DYN = 42;
  /** RegularExpression Id. */
  int KW_ABSTRACT = 43;
  /** RegularExpression Id. */
  int KW_BECOME = 44;
  /** RegularExpression Id. */
  int KW_BOX = 45;
  /** RegularExpression Id. */
  int KW_DO = 46;
  /** RegularExpression Id. */
  int KW_FINAL = 47;
  /** RegularExpression Id. */
  int KW_MACRO = 48;
  /** RegularExpression Id. */
  int KW_OVERRIDE = 49;
  /** RegularExpression Id. */
  int KW_PRIV = 50;
  /** RegularExpression Id. */
  int KW_TYPEOF = 51;
  /** RegularExpression Id. */
  int KW_UNSIZED = 52;
  /** RegularExpression Id. */
  int KW_VIRTUAL = 53;
  /** RegularExpression Id. */
  int KW_YIELD = 54;
  /** RegularExpression Id. */
  int KW_TRY = 55;
  /** RegularExpression Id. */
  int STRING = 56;
  /** RegularExpression Id. */
  int DIGIT = 57;
  /** RegularExpression Id. */
  int DIGITS = 58;
  /** RegularExpression Id. */
  int INTEGER = 59;
  /** RegularExpression Id. */
  int REAL = 60;
  /** RegularExpression Id. */
  int PLUS = 61;
  /** RegularExpression Id. */
  int MINUS = 62;
  /** RegularExpression Id. */
  int STAR = 63;
  /** RegularExpression Id. */
  int SLASH = 64;
  /** RegularExpression Id. */
  int PERCENT = 65;
  /** RegularExpression Id. */
  int CARET = 66;
  /** RegularExpression Id. */
  int NOT = 67;
  /** RegularExpression Id. */
  int AND = 68;
  /** RegularExpression Id. */
  int OR = 69;
  /** RegularExpression Id. */
  int ANDAND = 70;
  /** RegularExpression Id. */
  int OROR = 71;
  /** RegularExpression Id. */
  int SHL = 72;
  /** RegularExpression Id. */
  int SHR = 73;
  /** RegularExpression Id. */
  int PLUSEQ = 74;
  /** RegularExpression Id. */
  int MINUSEQ = 75;
  /** RegularExpression Id. */
  int STAREQ = 76;
  /** RegularExpression Id. */
  int SLASHEQ = 77;
  /** RegularExpression Id. */
  int PERCENTEQ = 78;
  /** RegularExpression Id. */
  int CARETEQ = 79;
  /** RegularExpression Id. */
  int ANDEQ = 80;
  /** RegularExpression Id. */
  int OREQ = 81;
  /** RegularExpression Id. */
  int SHLEQ = 82;
  /** RegularExpression Id. */
  int SHREQ = 83;
  /** RegularExpression Id. */
  int EQ = 84;
  /** RegularExpression Id. */
  int EQEQ = 85;
  /** RegularExpression Id. */
  int NE = 86;
  /** RegularExpression Id. */
  int GT = 87;
  /** RegularExpression Id. */
  int LT = 88;
  /** RegularExpression Id. */
  int GE = 89;
  /** RegularExpression Id. */
  int LE = 90;
  /** RegularExpression Id. */
  int AT = 91;
  /** RegularExpression Id. */
  int UNDERSCORE = 92;
  /** RegularExpression Id. */
  int DOT = 93;
  /** RegularExpression Id. */
  int DOTDOT = 94;
  /** RegularExpression Id. */
  int DOTDOTDOT = 95;
  /** RegularExpression Id. */
  int DOTDOTEQ = 96;
  /** RegularExpression Id. */
  int COMMA = 97;
  /** RegularExpression Id. */
  int SEMI = 98;
  /** RegularExpression Id. */
  int COLON = 99;
  /** RegularExpression Id. */
  int PATHSEP = 100;
  /** RegularExpression Id. */
  int RARROW = 101;
  /** RegularExpression Id. */
  int FATARROW = 102;
  /** RegularExpression Id. */
  int LARROW = 103;
  /** RegularExpression Id. */
  int POUND = 104;
  /** RegularExpression Id. */
  int DOLLAR = 105;
  /** RegularExpression Id. */
  int QUESTION = 106;
  /** RegularExpression Id. */
  int TILDE = 107;
  /** RegularExpression Id. */
  int LBRACE = 108;
  /** RegularExpression Id. */
  int RBRACE = 109;
  /** RegularExpression Id. */
  int LBRACKET = 110;
  /** RegularExpression Id. */
  int RBRACKET = 111;
  /** RegularExpression Id. */
  int LPAREN = 112;
  /** RegularExpression Id. */
  int RPAREN = 113;
  /** RegularExpression Id. */
  int LINE_COMMENT = 114;
  /** RegularExpression Id. */
  int BLOCK_COMMENTS = 115;
  /** RegularExpression Id. */
  int IDENTIFIER_END = 116;
  /** RegularExpression Id. */
  int IDENTIFIER = 117;
  /** RegularExpression Id. */
  int IDENTIFIER_ERROR_START = 118;
  /** RegularExpression Id. */
  int REAL_NUMBER_ERROR_MALFORMED = 119;
  /** RegularExpression Id. */
  int STRING_ERROR_UNTERMINATED = 120;
  /** RegularExpression Id. */
  int PUNCTUATION_ERROR_INVALID = 121;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"as\"",
    "\"break\"",
    "\"const\"",
    "\"continue\"",
    "\"crate\"",
    "\"else\"",
    "\"enum\"",
    "\"extern\"",
    "\"false\"",
    "\"fn\"",
    "\"for\"",
    "\"if\"",
    "\"impl\"",
    "\"in\"",
    "\"let\"",
    "\"loop\"",
    "\"match\"",
    "\"mod\"",
    "\"move\"",
    "\"mut\"",
    "\"pub\"",
    "\"ref\"",
    "\"return\"",
    "\"self\"",
    "\"Self\"",
    "\"static\"",
    "\"struct\"",
    "\"super\"",
    "\"trait\"",
    "\"true\"",
    "\"type\"",
    "\"unsafe\"",
    "\"use\"",
    "\"where\"",
    "\"while\"",
    "\"async\"",
    "\"await\"",
    "\"dyn\"",
    "\"abstract\"",
    "\"become\"",
    "\"box\"",
    "\"do\"",
    "\"final\"",
    "\"macro\"",
    "\"override\"",
    "\"priv\"",
    "\"typeof\"",
    "\"unsized\"",
    "\"virtual\"",
    "\"yield\"",
    "\"try\"",
    "<STRING>",
    "<DIGIT>",
    "<DIGITS>",
    "<INTEGER>",
    "<REAL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"&&\"",
    "\"||\"",
    "\"<<\"",
    "\">>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"^=\"",
    "\"&=\"",
    "\"|=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"@\"",
    "\"_\"",
    "\".\"",
    "\"..\"",
    "\"...\"",
    "\"..=\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"::\"",
    "\"->\"",
    "\"=>\"",
    "\"<-\"",
    "\"#\"",
    "\"$\"",
    "\"?\"",
    "\"~\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<LINE_COMMENT>",
    "<BLOCK_COMMENTS>",
    "<IDENTIFIER_END>",
    "<IDENTIFIER>",
    "<IDENTIFIER_ERROR_START>",
    "<REAL_NUMBER_ERROR_MALFORMED>",
    "<STRING_ERROR_UNTERMINATED>",
    "<PUNCTUATION_ERROR_INVALID>",
  };

}
