package unioeste.compiladores.lex;/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int KW_AS = 7;
  /** RegularExpression Id. */
  int KW_BREAK = 8;
  /** RegularExpression Id. */
  int KW_CONST = 9;
  /** RegularExpression Id. */
  int KW_CONTINUE = 10;
  /** RegularExpression Id. */
  int KW_CRATE = 11;
  /** RegularExpression Id. */
  int KW_ELSE = 12;
  /** RegularExpression Id. */
  int KW_ENUM = 13;
  /** RegularExpression Id. */
  int KW_EXTERN = 14;
  /** RegularExpression Id. */
  int KW_FALSE = 15;
  /** RegularExpression Id. */
  int KW_FN = 16;
  /** RegularExpression Id. */
  int KW_FOR = 17;
  /** RegularExpression Id. */
  int KW_IF = 18;
  /** RegularExpression Id. */
  int KW_IMPL = 19;
  /** RegularExpression Id. */
  int KW_IN = 20;
  /** RegularExpression Id. */
  int KW_LET = 21;
  /** RegularExpression Id. */
  int KW_LOOP = 22;
  /** RegularExpression Id. */
  int KW_MATCH = 23;
  /** RegularExpression Id. */
  int KW_MOD = 24;
  /** RegularExpression Id. */
  int KW_MOVE = 25;
  /** RegularExpression Id. */
  int KW_MUT = 26;
  /** RegularExpression Id. */
  int KW_PUB = 27;
  /** RegularExpression Id. */
  int KW_REF = 28;
  /** RegularExpression Id. */
  int KW_RETURN = 29;
  /** RegularExpression Id. */
  int KW_SELFVALUE = 30;
  /** RegularExpression Id. */
  int KW_SELFTYPE = 31;
  /** RegularExpression Id. */
  int KW_STATIC = 32;
  /** RegularExpression Id. */
  int KW_STRUCT = 33;
  /** RegularExpression Id. */
  int KW_SUPER = 34;
  /** RegularExpression Id. */
  int KW_TRAIT = 35;
  /** RegularExpression Id. */
  int KW_TRUE = 36;
  /** RegularExpression Id. */
  int KW_TYPE = 37;
  /** RegularExpression Id. */
  int KW_UNSAFE = 38;
  /** RegularExpression Id. */
  int KW_USE = 39;
  /** RegularExpression Id. */
  int KW_WHERE = 40;
  /** RegularExpression Id. */
  int KW_WHILE = 41;
  /** RegularExpression Id. */
  int KW_ASYNC = 42;
  /** RegularExpression Id. */
  int KW_AWAIT = 43;
  /** RegularExpression Id. */
  int KW_DYN = 44;
  /** RegularExpression Id. */
  int KW_ABSTRACT = 45;
  /** RegularExpression Id. */
  int KW_BECOME = 46;
  /** RegularExpression Id. */
  int KW_BOX = 47;
  /** RegularExpression Id. */
  int KW_DO = 48;
  /** RegularExpression Id. */
  int KW_FINAL = 49;
  /** RegularExpression Id. */
  int KW_MACRO = 50;
  /** RegularExpression Id. */
  int KW_OVERRIDE = 51;
  /** RegularExpression Id. */
  int KW_PRIV = 52;
  /** RegularExpression Id. */
  int KW_TYPEOF = 53;
  /** RegularExpression Id. */
  int KW_UNSIZED = 54;
  /** RegularExpression Id. */
  int KW_VIRTUAL = 55;
  /** RegularExpression Id. */
  int KW_YIELD = 56;
  /** RegularExpression Id. */
  int KW_TRY = 57;
  /** RegularExpression Id. */
  int PLUS = 58;
  /** RegularExpression Id. */
  int MINUS = 59;
  /** RegularExpression Id. */
  int STAR = 60;
  /** RegularExpression Id. */
  int SLASH = 61;
  /** RegularExpression Id. */
  int PERCENT = 62;
  /** RegularExpression Id. */
  int CARET = 63;
  /** RegularExpression Id. */
  int NOT = 64;
  /** RegularExpression Id. */
  int AND = 65;
  /** RegularExpression Id. */
  int OR = 66;
  /** RegularExpression Id. */
  int ANDAND = 67;
  /** RegularExpression Id. */
  int OROR = 68;
  /** RegularExpression Id. */
  int SHL = 69;
  /** RegularExpression Id. */
  int SHR = 70;
  /** RegularExpression Id. */
  int PLUSEQ = 71;
  /** RegularExpression Id. */
  int MINUSEQ = 72;
  /** RegularExpression Id. */
  int STAREQ = 73;
  /** RegularExpression Id. */
  int SLASHEQ = 74;
  /** RegularExpression Id. */
  int PERCENTEQ = 75;
  /** RegularExpression Id. */
  int CARETEQ = 76;
  /** RegularExpression Id. */
  int ANDEQ = 77;
  /** RegularExpression Id. */
  int OREQ = 78;
  /** RegularExpression Id. */
  int SHLEQ = 79;
  /** RegularExpression Id. */
  int SHREQ = 80;
  /** RegularExpression Id. */
  int EQ = 81;
  /** RegularExpression Id. */
  int EQEQ = 82;
  /** RegularExpression Id. */
  int NE = 83;
  /** RegularExpression Id. */
  int GT = 84;
  /** RegularExpression Id. */
  int LT = 85;
  /** RegularExpression Id. */
  int GE = 86;
  /** RegularExpression Id. */
  int LE = 87;
  /** RegularExpression Id. */
  int AT = 88;
  /** RegularExpression Id. */
  int UNDERSCORE = 89;
  /** RegularExpression Id. */
  int DOT = 90;
  /** RegularExpression Id. */
  int DOTDOT = 91;
  /** RegularExpression Id. */
  int DOTDOTDOT = 92;
  /** RegularExpression Id. */
  int DOTDOTEQ = 93;
  /** RegularExpression Id. */
  int COMMA = 94;
  /** RegularExpression Id. */
  int SEMI = 95;
  /** RegularExpression Id. */
  int COLON = 96;
  /** RegularExpression Id. */
  int PATHSEP = 97;
  /** RegularExpression Id. */
  int RARROW = 98;
  /** RegularExpression Id. */
  int FATARROW = 99;
  /** RegularExpression Id. */
  int LARROW = 100;
  /** RegularExpression Id. */
  int POUND = 101;
  /** RegularExpression Id. */
  int DOLLAR = 102;
  /** RegularExpression Id. */
  int QUESTION = 103;
  /** RegularExpression Id. */
  int TILDE = 104;
  /** RegularExpression Id. */
  int LBRACE = 105;
  /** RegularExpression Id. */
  int RBRACE = 106;
  /** RegularExpression Id. */
  int LBRACKET = 107;
  /** RegularExpression Id. */
  int RBRACKET = 108;
  /** RegularExpression Id. */
  int LPAREN = 109;
  /** RegularExpression Id. */
  int RPAREN = 110;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "\"as\"",
    "\"break\"",
    "\"const\"",
    "\"continue\"",
    "\"crate\"",
    "\"else\"",
    "\"enum\"",
    "\"extern\"",
    "\"false\"",
    "\"fn\"",
    "\"for\"",
    "\"if\"",
    "\"impl\"",
    "\"in\"",
    "\"let\"",
    "\"loop\"",
    "\"match\"",
    "\"mod\"",
    "\"move\"",
    "\"mut\"",
    "\"pub\"",
    "\"ref\"",
    "\"return\"",
    "\"self\"",
    "\"Self\"",
    "\"static\"",
    "\"struct\"",
    "\"super\"",
    "\"trait\"",
    "\"true\"",
    "\"type\"",
    "\"unsafe\"",
    "\"use\"",
    "\"where\"",
    "\"while\"",
    "\"async\"",
    "\"await\"",
    "\"dyn\"",
    "\"abstract\"",
    "\"become\"",
    "\"box\"",
    "\"do\"",
    "\"final\"",
    "\"macro\"",
    "\"override\"",
    "\"priv\"",
    "\"typeof\"",
    "\"unsized\"",
    "\"virtual\"",
    "\"yield\"",
    "\"try\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"&&\"",
    "\"||\"",
    "\"<<\"",
    "\">>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"^=\"",
    "\"&=\"",
    "\"|=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"@\"",
    "\"_\"",
    "\".\"",
    "\"..\"",
    "\"...\"",
    "\"..=\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"::\"",
    "\"->\"",
    "\"=>\"",
    "\"<-\"",
    "\"#\"",
    "\"$\"",
    "\"?\"",
    "\"~\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
  };

}
